[package]
name    = "miniseed"
version = "1.0.0"
authors = ["Brian Savage <savage13@gmail.com>"]
description = "MiniSEED library for rust"
repository = "https://github.com/savage13/miniseed"
homepage = "https://github.com/savage13/miniseed"
documentation = "https://docs.rs/miniseed/"
readme = "README.md"
keywords = ["miniseed", "iris", "seismology"]
license = "MIT"
build = "build.rs"

[dependencies]
chrono = "*"
glob   = "*"
libc   = "*"
num    = "*"

[build-dependencies]
git2 = "*"

